### ISSUE TITLE
So how does it work?

### ISSUE THREAD

**Issue by animemandir** [dentolos19/Otakulore#1]
So how does it work? I mean, I don't see any demo site here, plus I never tried .net.
Can you show me how to install the dependencies and run this project?

**Comment by dentolos19** [comment]
The project was incomplete so there wasn't a demo or anything like that.

So, in order to try out this app for yourself, follow the instructions I've written below...

1. Install Visual Studio 2019/2022 from [here](https://visualstudio.microsoft.com)
2. Install the workload: Universal Windows Platform Development
![](https://user-images.githubusercontent.com/63337204/132160826-121cde02-9959-4cb7-ab5b-cf396bfd2ead.png)
4. Clone the repository and open the solution: `Otakulore.sln`
5. Restore the NuGet packages (optional; it triggers itself when built)
6. Run the project via `Local Machine`
![](https://user-images.githubusercontent.com/63337204/132161149-a4e07eb2-9b0d-48a4-98c0-4d83284820d8.png)

**Comment by animemandir** [comment]
Ah, ic, I will run it right away.
I hope you can complete the project.
Don't give up on it, it's awesome.
Also, How how can you host a .net or .sln thing on the web?

**Comment by animemandir** [comment]
https://github.com/dentolos19/Otakulore/issues/1#issuecomment-913332909
bruh ....that software is costing me 16Gb lol.
I hop you can make it is react or nextjs

**Comment by dentolos19** [comment]
> I hope you can complete the project.
> Don't give up on it, it's awesome.

Ah thanks. I only work on the project in my spare time.

> Also, How how can you host a .net or .sln thing on the web?

Sorry, I don't understand what you mean.

> bruh ....that software is costing me 16Gb lol.

Well it's just 16GB. 😏

> I hop you can make it is react or nextjs

Also sorry, I can only program in C# but I am still continuing to learn more.

**Comment by dentolos19** [comment]
If there isn't anything else, I'll be closing this issue.
