### ISSUE TITLE
Couple of suggestions 

### ISSUE THREAD

**Issue by iCeY3** [dentolos19/Otakulore#4]
Nice app, i like the uniqueness of the UI/UX
If may suggest some stuff

1- providers: 9anime.id , allanime.site , zoro.to
2- MAL integration
3- built in player

And thanks again

**Comment by dentolos19** [comment]
Thanks for your input.

From your suggestions...

1. I'll be sure to update my provider support in the future and I'll keep in mind of your list.
2. This app is heavily dependent on AniList, however, it is possible because AniList's API provides MAL IDs as well. So I'll work on this in the future if possible.
3. Since .NET MAUI has just been recently released, some time will be needed before [MediaElement](https://github.com/dotnet/maui/issues/6764#issuecomment-1115807728) or [LibVLCSharp](https://code.videolan.org/videolan/LibVLCSharp/-/issues/346) supports .NET MAUI, so let's be patient.

**Comment by iCeY3** [comment]
Keep up the good work

Thanks

**Comment by MrConqueror** [comment]
> Nice app, i like the uniqueness of the UI/UX If may suggest some stuff
> 
> 1- providers: 9anime.id , allanime.site , zoro.to 2- MAL integration 3- built in player
> 
> And thanks again

nice suggestions

**Comment by dentolos19** [comment]
This project is being shut down, see `README.md` for more info.
